# Generated by Django 4.1.6 on 2023-02-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_reservation_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
    ]
