# Generated by Django 4.1.6 on 2023-02-11 11:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain
import property.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Property Category',
                'verbose_name_plural': 'Property Categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True)),
            ],
            options={
                'verbose_name': 'Property Feature Category',
                'verbose_name_plural': 'Property Feature Categories',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('location', location_field.models.plain.PlainLocationField(max_length=250)),
                ('number_of_bedrooms', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('number_of_beds', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('number_of_baths', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('capacity_for_adults', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('capacity_for_children', models.PositiveSmallIntegerField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=6)),
                ('available', models.BooleanField()),
                ('available_from', models.DateTimeField()),
                ('available_to', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='property.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('rate', models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_reviews', to='property.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property Review',
                'verbose_name_plural': 'Property Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='property/photos', validators=[property.validators.validate_image_size, django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
                ('video', models.FileField(upload_to='property/videos', validators=[property.validators.validate_video_size, django.core.validators.FileExtensionValidator(['mp4', 'webm', 'mkv', 'flv', 'wmv'])])),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_media', to='property.property')),
            ],
            options={
                'verbose_name': 'Property Media',
                'verbose_name_plural': 'Property Media',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('feature_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_features', to='property.featurecategory')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='property.property')),
            ],
            options={
                'verbose_name': 'Property Feature',
                'verbose_name_plural': 'Property Features',
            },
        ),
    ]
