# Generated by Django 4.1.6 on 2023-02-04 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('number_of_bedrooms', models.PositiveSmallIntegerField()),
                ('number_of_beds', models.PositiveSmallIntegerField()),
                ('number_of_baths', models.PositiveSmallIntegerField()),
                ('capacity_for_adults', models.PositiveSmallIntegerField()),
                ('capacity_for_children', models.PositiveSmallIntegerField()),
                ('available', models.BooleanField()),
                ('available_from', models.DateTimeField()),
                ('available_to', models.DateTimeField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cancellation_policy', models.CharField(choices=[('Free Cancellation', 'Free Cancellation'), ('Paid Cancellation', 'Paid Cancellation')], default='Free Cancellation', max_length=50)),
                ('cancellation_fee', models.DecimalField(decimal_places=2, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
    ]
