# Generated by Django 4.1.6 on 2023-02-08 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='host_user',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='property',
            name='cancellation_fee',
        ),
        migrations.RemoveField(
            model_name='property',
            name='cancellation_policy',
        ),
        migrations.RemoveField(
            model_name='property',
            name='guest_user',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price_per_night',
        ),
    ]
