# Generated by Django 4.1.6 on 2023-02-11 12:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='capacity_for_children',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='property.category'),
        ),
    ]
