# Generated by Django 4.1.6 on 2023-02-11 14:49

import django.core.validators
from django.db import migrations, models
import property.validators


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_media_property_alter_property_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='video',
            field=models.FileField(blank=True, upload_to='property/videos', validators=[property.validators.validate_video_size, django.core.validators.FileExtensionValidator(['mp4', 'webm', 'mkv', 'flv', 'wmv'])]),
        ),
    ]
